manifest:
  version: "1.2"

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v4.3.0
      path: zephyr
      import: false
      west-commands: scripts/west-commands.yml
    - name: cmsis
      remote: zephyrproject
      revision: 512cc7e895e8491696b61f7ba8066b4a182569b8
      path: third_party/hal/cmsis
    - name: hal_stm32
      remote: zephyrproject
      revision: 286dd285b5bb4fddafdfff27b5405264e5a61bfe
      path: third_party/hal/stm32
    - name: segger
      remote: zephyrproject
      revision: 9f08435a79d41133d7046b7c59d1b25929eda450
      path: modules/debug/segger

  self:
    path: manifest
