CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PINCTRL=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_RING_BUFFER=y
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_CAN=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_PWM=y
CONFIG_ASSERT=y

CONFIG_RSCF_PROFILE_MINIMAL_BRINGUP=y
CONFIG_RSCF_EVENT_BUS=y
CONFIG_RSCF_DAEMON_SERVICE=y
CONFIG_RSCF_HEALTH_SERVICE=y
